Smart/modules/Smart.PL.WebUI.Frontend/Controllers/HomeController.cs
using Microsoft.Practices.ServiceLocation;
using Smart.BL.Entities;
using Smart.BL.Services.Abstract;
using Smart.PL.WebUI.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Smart.PL.WebUI.Frontend.Controllers
{
    public class HomeController : BaseController
    {

        #region Fields

        #endregion

        #region Constructors

        public HomeController(IServiceLocator serviceLocator): base(serviceLocator)
        {
        }

        #endregion

        #region Web Actions

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetStartupMarkets()
        {
            IStartupMarketService marketService = this.ServiceLocator.GetInstance<IStartupMarketService>();
            return Json(new
            {
                startupMarkets = marketService.GetMostPopular()
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetMostPopularJobMarkets()
        {
            IJobMarketService marketService = this.ServiceLocator.GetInstance<IJobMarketService>();
            return Json(new
            {
                jobMarkets = marketService.GetMostPopular()
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetNotableInvestors()
        {
            IInvestorService investorService = this.ServiceLocator.GetInstance<IInvestorService>();
            return Json(new
            {
                notableInvestors = investorService.GetNotableInvestors()
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetTopRatedStartups()
        {
            IStartupService startupService = this.ServiceLocator.GetInstance<IStartupService>();
            return Json(new
            {
                topRatedStartups = startupService.GetTopRated()
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetStatistic()
        {
            IStatisticService statisticService = this.ServiceLocator.GetInstance<IStatisticService>();
            return Json(new
            {
                statistic = statisticService.GetStatistic()
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetActionDescription()
        {
            ICallToActionService actionService = this.ServiceLocator.GetInstance<ICallToActionService>();
            return Json(new
            {
                descriptions = actionService.GetDescription()
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetTrandingStartups()
        {
            IStartupService service = this.ServiceLocator.GetInstance<IStartupService>();
            return Json(new
            {
                startups = service.GetTrandingStartups()
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetPopularStartups()
        {
            IStartupService service = this.ServiceLocator.GetInstance<IStartupService>();
            return Json(new
            {
                startups = service.GetPopularStartups()
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetTalents()
        {
            ITalentService service = this.ServiceLocator.GetInstance<ITalentService>();
            return Json(new
            {
                talents = service.GetTalents()
            }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Helpers

        #endregion

    }
}

Smart/modules/Smart.PL.WebUI.Frontend/Controllers/TalentRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Smart.PL.WebUI.Frontend.Controllers
{
    public class TalentRegistrationController : Controller
    {
        // GET: TalentRegistration
        public ActionResult Index()
        {
            return View();
        }
    }
}

Smart/modules/Smart.PL.WebUI.Frontend/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/Layout.cshtml";
    
}

@section HeadStyles
{    
    <link href="~/Styles/carousel-bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Styles/nia-flipping.css" />
    <link rel="stylesheet" href="~/Styles/nia-layout.css" />
}

@section HeadScripts
{

}

@section FootScripts
{    
    <script src="~/Scripts/libs/angular-ui/ui-bootstrap.js"></script>
    <script src="~/Scripts/libs/angular-ui/ui-bootstrap-tpls.js"></script>
   
    <script src="~/Scripts/app/shared/smart.module.js"></script>
    <script src="~/Scripts/app/shared/slicing.service.js"></script>

    <script src="~/Scripts/app/pages/home/home.module.js"></script>      

    <script src="~/Scripts/app/pages/home/home.controller.js"></script>
    <script src="~/Scripts/app/pages/home/presentation-bar.controller.js"></script>
    <script src="~/Scripts/app/pages/home/startup-market.service.js"></script>
    <script src="~/Scripts/app/pages/home/job-market.service.js"></script>
    <script src="~/Scripts/app/pages/home/investor.service.js"></script>
    <script src="~/Scripts/app/pages/home/startup.service.js"></script>
    <script src="~/Scripts/app/pages/home/statistic.service.js"></script>
    <script src="~/Scripts/app/pages/home/statistic.controller.js"></script>
    <script src="~/Scripts/app/pages/home/call-to-action.service.js"></script>
    <script src="~/Scripts/app/pages/home/call-to-action.controller.js"></script>
    <script src="~/Scripts/app/pages/home/tranding-startups.service.js"></script>
    <script src="~/Scripts/app/pages/home/tranding-startups.controller.js"></script>
    <script src="~/Scripts/app/pages/home/popular-startup.service.js"></script>
    <script src="~/Scripts/app/pages/home/popular-startup.controller.js"></script>
    <script src="~/Scripts/app/pages/home/talent.service.js"></script>
    <script src="~/Scripts/app/pages/home/talent.controller.js"></script>
    <script src="~/Scripts/app/pages/home/notable-investor.controller.js"></script>    
    <script src="~/Scripts/app/shared/resizable.directive.js"></script>

}

@section Header
{
    @Html.Partial("_Header")
}

<div data-ng-app="homeModule">
    @Html.Partial("_Statistic")
    @Html.Partial("_PresentationBar")
    @Html.Partial("_CallToAction")
    @Html.Partial("_ContactUs")

    <div class="content clearfix" id="startup_area">
        <div class="center">
            <div class="row"></div>
            <div class="title_area">SMARTUP CELL</div>
            <div class="row"></div>
            <div class="title_bold_area">TRENDING STARTUPS</div>
            <a href="#" class="botton_all">See more...</a>
            <div class="row"></div>
            @Html.Partial("_TrandingStartups")
        </div>
    </div>
    <div class="content clearfix" id="startup_popular_area">
        <div class="center">
            <div class="row"></div>
            <div class="title_bold_area">POPULAR STARTUPS</div>
            <div class="botton_all">See more...</div>
            <div class="row"></div>
            @Html.Partial("_PopularStartups")
        </div>
    </div>
    <div class="row"></div>
    <div class="content clearfix" id="notib_investors_area">
        <div class="center">
            <div class="row"></div>
            <div class="title_area">NOTIBLE INVESTORS</div>
            <div class="botton_all">See more...</div>
            <div class="row"></div>

            @Html.Partial("_NotibleInvestors")

        </div>
    </div>
    <div class="row"></div>
    <div class="content clearfix" id="talents_area">
        <div class="center">
            <div class="row"></div>
            <div class="title_area">TALENTS CELLS</div>
            <div class="row"></div>
            <div class="title_bold_area">TOP RATED TALENTS</div>
            <div class="botton_all">See more...</div>
            <div class="row"></div>
            @Html.Partial("_Talents")
        </div>
    </div>
</div>

@section Footer
{
    @Html.Partial("_Footer")
}

Smart/modules/Smart.PL.WebUI.Frontend/Views/Home/PresentationBar.Partial.cshtml
<div data-ng-controller="PresentationBarController as presentBar">
    <div class="startup-markets-wrapper">
        <h2>Startup Markets</h2>
        <div class="startup-markets">
            <div data-ng-repeat="market in presentBar.startupMarkets">{{ market.Name }}</div>
        </div>
    </div>

    <div class="job-markets-wrapper">
        <h2>Job Markets</h2>
        <div class="job-markets">
            <div data-ng-repeat="market in presentBar.jobMarkets">{{ market.Name }}</div>
        </div>
    </div>

    <div class="notable-investors-wrapper">
        <h2>Notable Investors</h2>
        <div class="notable-investors">
            <div data-ng-repeat="investor in presentBar.notableInvestors">{{ investor.Name }}</div>
        </div>
    </div>

    <div class="top-rated-startups-wrapper">
        <h2>Top Rated Startups</h2>
        <div class="top-rated-startups">
            <div data-ng-repeat="startup in presentBar.topRatedStartups">{{ startup.Name }}</div>
        </div>
    </div>

</div>

Smart/modules/Smart.PL.WebUI.Frontend/Views/Home/Statistic.Partial.cshtml
<div data-ng-controller="StatisticController as controller">
    <div class="statistic-wrapper">
        <h2>Statistic</h2>
        <div class="statistic">
            <div data-ng-repeat="item in controller.statistic">{{ item.Value }} {{item.Text}}</div>
        </div>
    </div>

</div>

Smart/modules/Smart.PL.WebUI.Frontend/Views/Home/_CallToAction.cshtml
<div class="content" id="get_started_area" data-ng-controller="CallToActionController as controller">
    <div class="center">
        <div class="row"></div>
        <div class="title_area">GET STARTED</div>
        <a href="#" class="botton_all">See more...</a>
        <div class="row"></div>
        <div class="botton_started_categories butt1">
            <div class="vert_text_started">
                {{ controller.descriptions.LaunchStartupDescription }}
            </div>
        </div>
        <div class="botton_started_categories">
            <a href='@Url.Action("Index", "TalentRegistration")' class="botton_block_get_start butt2">Find your Job</a>
        </div>
        <div class="botton_started_categories butt3">
            <div class="vert_text_started">
                {{ controller.descriptions.FindYourJobDescription }}
            </div>
        </div>
        <div class="botton_started_categories">
            <a href="#" class="botton_block_get_start butt4">
                Start to Invest
            </a>
        </div>
        <div class="bar_triangle">
            <div class="triangle-down trian1"></div>
            <div class="triangle-up trian2"></div>
            <div class="triangle-down trian3"></div>
            <div class="triangle-up trian4"></div>
        </div>
        <div class="botton_started_categories">
            <a href="#" class="botton_block_get_start butt1">
                Launch Startup
            </a>
        </div>

        <div class="botton_started_categories butt2">
            <div class="vert_text_started">
                {{ controller.descriptions.PostJobDescription }}
            </div>
        </div>
        <div class="botton_started_categories">
            <a href="#" class="botton_block_get_start butt3">
                Post a Job
            </a>
        </div>

        <div class="botton_started_categories butt4">
            <div class="vert_text_started">
                {{ controller.descriptions.StartToInvestDescription }}
            </div>
        </div>
        <div class="row"></div>
    </div>
    <div class="row"></div>
</div>

Smart/modules/Smart.PL.WebUI.Frontend/Views/Home/_ContactUs.cshtml
<div class="content" id="text_get_start">
    <div class="center">
        You are in the world’s marketplace where developers find or post a job,
        <br>join R&D teams, and share own innovative ideas to launch startup companies.
    </div>
</div>

Smart/modules/Smart.PL.WebUI.Frontend/Views/Home/_Footer.cshtml
<div class="row"></div>
<div id="footer">
    <div class="content" id="footer_content">
        <div class="center">
            <div class="colum_foot">

                <div class="colum_foot_title">
                    About Us
                </div>
                <div class="colum_link">
                    How it is work
                </div>
                <div class="colum_link">
                    Stats
                </div>
                <div class="colum_link">
                    Contacts
                </div>
                <div id="email"></div>
                <div id="twiter"></div>
                <div id="rss"></div>
            </div>

            <div class="colum_foot">
                <div class="colum_foot_title">
                    Help
                </div>
                <div class="colum_link">
                    Topics
                </div>
                <div class="colum_link">
                    FAQ
                </div>
                <div class="colum_link">
                    Blog
                </div>
            </div>

            <div class="colum_foot">
                <div class="colum_foot_title">
                    Discover
                </div>
                <div class="colum_link">
                    Startups
                </div>
                <div class="colum_link">
                    FAQ
                </div>
                <div class="colum_link">
                    Investors
                </div>
                <div class="colum_link">
                    Jobs
                </div>
                <div class="colum_link">
                    Freelancers
                </div>
            </div>

        </div>
    </div>
    <div class="row"></div>
</div>
<div class="row"></div>

Smart/modules/Smart.PL.WebUI.Frontend/Views/Home/_Header.cshtml
<div id="header">
    <div class="content" id="header_content">
        <a href="#">
            <div id="logo"></div>
        </a>
        <div class="header_text">
            <a href="#">INVESTMENTS</a>
            <a href="#">JOBS</a>
            <a href="#">HOW IT WORKS</a>
        </div>
        <div class="find_area"></div>
        <a href="#">
            <div id="magnifying_glass"></div>
        </a>
        <div class="small_header_text">
            <a href="#">Sign In </a>
            <a href="#">Log In...</a>
        </div>
    </div>

</div>

Smart/modules/Smart.PL.WebUI.Frontend/Views/Home/_NotibleInvestors.cshtml
<div id="MFA" ng-controller="NotableInvestorController as controller" resizable>
    <uib-carousel interval="myInterval" no-wrap="noWrapSlides">
        <uib-slide ng-repeat="slide in controller.slides" active="slide.active" index="slide.id">
            <ul class="nia-part">
                <li class="flip-container " ng-repeat="item in slide.items" ontouchstart="this.classList.toggle('hover');">
                    <div class="flipper">
                        <div class="front">
                            <div class="avatar" style="background-image: url({{item.PhotoUrl}})"></div>
                            <div class="quotation">{{item.ShortQuotation}}</div>
                            <div class="title"><span>{{item.Name}}</span><span>{{item.Position}}</span></div>
                        </div>
                        <div class="back">
                            {{item.LargeQuotation}}
                        </div>
                    </div>
                </li>
            </ul>
        </uib-slide>
    </uib-carousel>
</div>

Smart/modules/Smart.PL.WebUI.Frontend/Views/Home/_PopularStartups.cshtml
<div data-ng-controller="PopularStartupsController as controller">
    <div class="flip-container" data-ng-repeat="startup in controller.startups">
        <div class="flipper">
            <div class="front">
                <div class="startup_cell">
                    <div class="startup_cell">
                        <img class="startup_img" ng-src="{{startup.LogoUrl}}" alt="Education">
                        <div class="startup_title">
                            {{startup.Title}}
                        </div>
                        <img class="face_startuper" ng-src="{{startup.Startuper.PhotoUrl}}">
                        <div class="line_cell">
                            <div class="startuper_name">{{startup.Startuper.Name}}</div>
                            <img class="flag_startup" ng-src="~/Styles/images/{{startup.Startuper.Counry | lowercase}}.jpg">
                            <span class="startuper_likes">{{startup.Startuper.Likes}}</span>
                            <img class="img_like" src="~/Styles/images/likes.png">
                            <div class="row"></div>
                        </div>
                        <div class="row"></div>
                        <div class="line_cell">
                            <div class="startuper_text">Round</div>
                            <div class="round_name">{{startup.Status}}</div>
                            <div class="start_team">Join Team!</div>
                            <div class="row"></div>
                        </div>
                        <div class="row"></div>
                        <div class="startuper_text">Categories</div>
                        <div data-ng-repeat="item in startup.Categories">
                            <div class="categories_name">{{item}}</div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="back">
                <div class="back_title">{{startup.BackTitle}}</div>
                <a href="#" class="back_content">
                    {{startup.BackContent}}
                    <span class="green_text"> Click cell for more info >></span>
                    <div class="row"></div>
                </a>

                <a href="#" class="back_button">
                    <div class="back_icon icon_Follow"></div>
                    Follow
                </a>
                <a href="#" class="back_button">
                    <div class="back_icon icon_Massege"></div>
                    Send Message
                </a>
                <a href="#" class="back_button">
                    <div class="back_icon icon_Share"></div>
                    Share
                </a>
                <a href="#" class="back_button">
                    <div class="back_icon icon_Like"></div>
                    Like
                </a>
            </div>
        </div>
    </div>
</div>

Smart/modules/Smart.PL.WebUI.Frontend/Views/Home/_PresentationBar.cshtml
<div class="content" id="presentation_bar_area" data-ng-controller="PresentationBarController as presentBar">

    @Html.Partial("_StartupMarkets")

    @*<div class="startup-markets-wrapper">
        <h2>Startup Markets</h2>
        <div class="startup-markets">
            <div data-ng-repeat="market in presentBar.startupMarkets">{{ market.Name }}</div>
        </div>
    </div>

    <div class="job-markets-wrapper">
        <h2>Job Markets</h2>
        <div class="job-markets">
            <div data-ng-repeat="market in presentBar.jobMarkets">{{ market.Name }}</div>
        </div>
    </div>

    <div class="notable-investors-wrapper">
        <h2>Notable Investors</h2>
        <div class="notable-investors">
            <div data-ng-repeat="investor in presentBar.notableInvestors">{{ investor.Name }}</div>
        </div>
    </div>

    <div class="top-rated-startups-wrapper">
        <h2>Top Rated Startups</h2>
        <div class="top-rated-startups">
            <div data-ng-repeat="startup in presentBar.topRatedStartups">{{ startup.Name }}</div>
        </div>
    </div>*@

</div>

Smart/modules/Smart.PL.WebUI.Frontend/Views/Home/_StartupMarkets.cshtml
<div class="center" ng-init="classes = ['butt1', 'butt0', 'butt3', 'butt0', 'butt0', 'butt2', 'butt0', 'butt4']">
    <div class="row"></div>
    <div class="title_area">STURTUPS MARKETS</div>
    <div class="botton_all">All Markets</div>
    <div class="row"></div>

    <a href="#" data-ng-repeat="market in presentBar.startupMarkets" ng-class="['bottom_categories', classes[$index]]">
        <img ng-src="{{ market.IconUrl }}" alt="{{ market.Name }}" />
        <span class="vert_text_categories">{{ market.Name }}</span>        
    </a>

</div>
<div class="row"></div>

Smart/modules/Smart.PL.WebUI.Frontend/Views/Home/_Talents.cshtml
<div data-ng-controller="TalentsController as controller">
    <div class="flip-container" data-ng-repeat="talent in controller.talents">
        <div class="flipper">
            <div class="front">
                <div class="talents_cell">
                    <img class="img_talents" ng-src="{{talent.PhotoUrl}}">
                    <div class="talent_title_text">
                        Ronald Brin
                    </div>
                    <img class="flag_startup" ng-src="{{talent.FlagUrl}}">
                    <div class="row"></div>
                    <div class="talent_skil_text">
                        {{talent.Title}}
                    </div>
                    <div class="talent_price_text">{{talent.Rate | currency:"$":0}}</div>
                    <div class="talent_price_time">/hr</div>
                    <div class="row"></div>
                    <div class="talent_job_success">Job Success</div>
                    <div class="talent_percent_success">{{talent.PercentSuccess}}%</div>
                    <div class="progress_bar">
                        <div class="progress" style="width:{{ talent.PercentSuccess }}%"></div>
                    </div>
                    <div class="statistic">
                        <div class="statistic_title">Work history</div>
                        <div class="statistic_value">{{talent.Jobs}}</div>
                        <div class="statistic_text">jobs</div>
                        <div class="row"></div>
                        <div class="statistic_title">Availability</div>
                        <div class="statistic_value">{{talent.Availability}}</div>
                        <div class="statistic_text">hrs per week</div>
                        <div class="row"></div>
                        <div class="statistic_title">Responce time</div>
                        <div class="statistic_value">{{talent.ResponceTime}}</div>
                        <div class="statistic_text">hrs</div>
                        <div class="row"></div>
                        <div class="statistic_title">Tests </div>
                        <div class="statistic_value">{{talent.Tests}} </div>
                        <div class="statistic_text">(</div>
                        <div class="statistic_value">{{talent.TestsSuccess}}%</div>
                        <div class="statistic_text"> success)</div>
                        <div class="row"></div>
                        <div class="statistic_title">{{talent.Language}} </div>
                        <div class="statistic_value">{{talent.LanguageLevel}} </div>
                        <div class="row"></div>
                    </div>
                    <div class="row"></div>
                    <div class="member_of">Member of</div>
                    <div class="member_corporation">{{talent.MemberOfCorporation}}</div>
                    <div class="row"></div>
                    <div class="experienced_in">
                        <div class="talent_experience">Experienced in</div>
                        <div class="experience" data-ng-repeat="item in talent.Categories">{{item}}</div>
                    </div>
                    <div class="row"></div>
                </div>
            </div>
            <div class="back">
                <div class="back_title">{{talent.BackTitle}}</div>
                <a href="#" class="back_content">
                    {{talent.BackContent}}
                    <span class="green_text"> Click cell for more info >></span>
                    <div class="row"></div>
                </a>

                <a href="#" class="back_button">
                    <div class="back_icon icon_See_profile"></div>
                    See Profile
                </a>
                <a href="#" class="back_button">
                    <div class="back_icon icon_Massege"></div>
                    Send Message
                </a>
                <a href="#" class="back_button">
                    <div class="back_icon icon_Save"></div>
                    Save
                </a>
            </div>
        </div>
    </div>
</div>

Smart/modules/Smart.PL.WebUI.Frontend/Views/Home/_TrandingStartups.cshtml
<div data-ng-controller="TrandingStartupsController as controller">
    <div class="flip-container" data-ng-repeat="startup in controller.startups">
        <div class="flipper">
            <div class="front">
                <div class="startup_cell">
                    <img class="startup_img" ng-src="{{startup.LogoUrl}}" alt="Education">
                    <div class="startup_title">{{startup.Title}}</div>
                    <img class="face_startuper" ng-src="{{startup.Startuper.PhotoUrl}}">
                    <div class="line_cell">
                        <div class="startuper_name">{{startup.Startuper.Name}}</div>
                        <img class="flag_startup" ng-src="~/Styles/images/{{startup.Startuper.Counry | lowercase}}.jpg">
                        <span class="startuper_likes">{{startup.Startuper.Likes}}</span>
                        <img class="img_like" src="~/Styles/images/likes.png">
                        <div class="row"></div>
                    </div>
                    <div class="startuper_text">Investor</div>
                    <div class="investor_name">{{startup.Investor}}</div>
                    <div class="row"></div>
                    <div class="progress_bar">
                        <div class="progress" style="width:{{ startup.InvestedFunds }}%"></div>
                    </div>
                    <div class="startup_values">
                        <div class="full_values">{{startup.InvestedFunds}}%</div>
                        <div class="title_values">founded</div>
                    </div>
                    <div class="startup_values">
                        <div class="full_values">{{startup.Pladged| currency:"$":0}}</div>
                        <div class="title_values">pladged</div>
                    </div>
                    <div class="startup_values">
                        <div class="full_values">{{startup.Backers}}</div>
                        <div class="title_values">backers</div>
                    </div>
                    <div class="startup_values">
                        <div class="full_values">{{startup.DaysToGo}}</div>
                        <div class="title_values">days to go</div>
                    </div>
                </div>
            </div>

            <div class="back">
                <div class="back_title">{{startup.BackTitle}}</div>
                <a href="#" class="back_content">
                    {{startup.BackContent}}
                    <span class="green_text"> Click cell for more info >></span>
                    <div class="row"></div>
                </a>

                <a href="#" class="back_button">
                    <div class="back_icon icon_Follow"></div>
                    Follow
                </a>
                <a href="#" class="back_button">
                    <div class="back_icon icon_Massege"></div>
                    Send Message
                </a>
                <a href="#" class="back_button">
                    <div class="back_icon icon_Share"></div>
                    Share
                </a>
                <a href="#" class="back_button">
                    <div class="back_icon icon_Like"></div>
                    Like
                </a>
            </div>

        </div>
    </div>
</div>


Smart/modules/Smart.PL.WebUI.Frontend/Views/Shared/Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE HTML>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
    <title>Develop future together!</title>

    <link rel="stylesheet" href="~/Styles/reset.css" />
    <link href="~/Styles/style.css" rel="stylesheet" />

    @RenderSection("HeadStyles", false)

    <script src="~/Scripts/Libs/angularjs/angular.js"></script>
    <script src="~/Scripts/libs/angularjs/angular-animate.js"></script>

    <script src="~/Scripts/Libs/jQuery/jquery-2.1.4.js"></script>

    @RenderSection("HeadScripts", false)

</head>
<body>
    <header>
        @RenderSection("Header", false)
    </header>
    <section>
        @RenderBody()
    </section>
    <footer>
        @RenderSection("Footer", false)
    </footer>
    @RenderSection("FootScripts", false)
</body>
</html>

Smart/modules/Smart.PL.WebUI.Frontend/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    @RenderSection("HeadStyles", false)

    <script src="~/Scripts/Libs/angularjs/angular.js"></script>
    <script src="~/Scripts/Libs/jQuery/jquery-2.1.4.js"></script>

    @RenderSection("HeadScripts", false)

</head>
<body>
    <div>
        @RenderBody()
    </div>
    @RenderSection("FootScripts", false)
</body>
</html>

Smart/modules/Smart.PL.WebUI.Frontend/Views/TalentRegistration/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<style type="text/css">
    .wrapper {
      border: 1px dashed #95a5a6;
      height: 56px;
      margin-top: 16px;
      border-radius: 4px;
      position: relative;
      font-size: 12px;
      width: 300px;
    }
    .wrapper h2 {
      text-align: center;
    }
</style>

<div ng-app="" >
    <div class="wrap" ng-init="content='talent'">
        <h1>Registration</h1>
        <form>
            <input id="talent" type="radio" name="content" ng-model="content" value="talent">
            <label for="talent">Talent</label>
            <br />
            <input id="companyContractor" type="radio" name="content" ng-model="content" value="companyContractor">
            <label for="companyContractor">Company Contractor</label>
        </form>

        <div class="wrapper">
            <h2 ng-show="content == 'talent'">Talent Registration!</h2>
            <h2 ng-show="content == 'companyContractor'">Company Contractor Registration!</h2>
        </div>
    </div>
</div>